version: 0.2

env:
  variables:
    NODE_VERSION: "20"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "🚀 Starting Frontend Build..."
      - echo "📅 Build started on `date`"
      - echo "📦 Node.js version:"
      - node --version
      - npm --version

  pre_build:
    commands:
      - echo "📋 Pre-build phase started"
      - cd frontend
      
      # Install dependencies with clean install
      - echo "📦 Installing frontend dependencies..."
      - npm ci
      
      # Verify react-scripts is installed
      - echo "🔍 Checking react-scripts installation..."
      - npm list react-scripts || echo "⚠️ react-scripts not found in dependencies"
      
      # Set environment variables
      - echo "🌍 Setting environment variables..."
      - echo "REACT_APP_API_URL=${REACT_APP_API_URL}" > .env
      - cat .env

  build:
    commands:
      - echo "🏗️ Build phase started"
      - cd frontend
      
      # Build the React application
      - echo "⚛️ Building React application..."
      - npm run build
      
      # Verify build directory exists
      - echo "🔍 Verifying build output..."
      - ls -la build/
      - echo "📊 Build size:"
      - du -sh build/

  post_build:
    commands:
      - echo "📤 Post-build phase started"
      - cd frontend
      
      # Deploy to S3
      - echo "☁️ Deploying to S3 bucket ${S3_BUCKET_NAME}"
      - aws s3 sync build/ s3://${S3_BUCKET_NAME} --delete
      
      # Invalidate CloudFront
      - echo "🔄 Invalidating CloudFront distribution ${CLOUDFRONT_DISTRIBUTION_ID}"
      - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"
      
      - echo "✅ Frontend deployed successfully to S3 + CloudFront!"
      - echo "📅 Completed: `date`"

artifacts:
  files:
    - 'frontend/build/**/*'
  name: frontend-build-artifacts

cache:
  paths:
    - 'frontend/node_modules/**/*'
