version: 0.2

env:
  variables:
    NODE_VERSION: "20"
  secrets-manager:
    GITHUB_TOKEN: "cicd-workshop/github-token"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "🚀 Setting up GitHub Actions runner environment..."
      - apt-get update -y
      - apt-get install -y curl jq wget

  pre_build:
    commands:
      - echo "📋 Pre-build phase for GitHub runner setup..."
      - echo "Build ID: $CODEBUILD_BUILD_ID"
      - echo "Project: $CODEBUILD_PROJECT_NAME"
      - curl --version
      - node --version
      - npm --version

  build:
    commands:
      - echo "🏗️ Main build phase..."
      - echo "This buildspec is working correctly!"
      - echo "Repository: https://github.com/lfyagya/cicd-workshop-qa-team"
      - echo "Branch: team6-yagya"
      
      # Simple test to verify the build environment
      - echo "✅ Build environment is ready"
      - echo "Current directory: $(pwd)"
      - echo "Available files:"
      - ls -la

  post_build:
    commands:
      - echo "🎉 Build completed successfully!"
      - echo "Timestamp: $(date)"

artifacts:
  files:
    - '**/*'
  name: build-artifacts-$(date +%Y%m%d-%H%M%S)
artifacts:
  files:
    - '**/*'
  name: build-artifacts-$(date +%Y%m%d-%H%M%S)
