name: Cypress E2E Tests

on:
  workflow_run:
    workflows: ["Frontend Deploy"]   # Match the name exactly
    types:
      - completed

jobs:
  e2e:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    env:
      CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASE_URL }}
      CYPRESS_API_URL: ${{ secrets.CYPRESS_API_URL }}

    steps:
      - name: Wait until frontend is live
        run: |
          echo "Waiting for frontend at $CYPRESS_BASE_URL..."
          for i in {1..20}; do
            if curl --silent --fail "$CYPRESS_BASE_URL"; then
              echo "Frontend is live!"
              break
            fi
            echo "Waiting 10 seconds..."
            sleep 10
          done

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./frontend
          install: false
          start: ''
          wait-on: ${{ secrets.CYPRESS_BASE_URL }}
          wait-on-timeout: 120
          config: baseUrl=${{ secrets.CYPRESS_BASE_URL }}
        env:
          CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASE_URL }}
          CYPRESS_API_URL: ${{ secrets.CYPRESS_API_URL }}
