name: Run Cypress E2E Tests on Live Site

on:
  push:
    branches:
      - team2-geeta

jobs:
  cypress-e2e:
    runs-on: ubuntu-latest

    env:
      CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASE_URL }}
      CYPRESS_API_URL: ${{ secrets.CYPRESS_API_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run Cypress E2E tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./frontend
          browser: chrome

      - name: Upload Cypress artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            frontend/cypress/screenshots
            frontend/cypress/videos

      - name: Upload Mochawesome HTML report (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: frontend/cypress/reports/html
