name: Cypress E2E on Live Site

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run Cypress tests on deployed site
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./frontend
          start: ''  # No need to start local server
