name: Deploy Frontend and Run E2E Tests

on:
  push:
    branches:
      - team2-geeta

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      CLOUDFRONT_DIST_ID: ${{ secrets.CLOUDFRONT_DIST_ID }}
      CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASE_URL }}
      CYPRESS_API_URL: ${{ secrets.CYPRESS_API_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ./frontend/node_modules
            ./e2e-tests/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Deploy frontend to S3
        run: aws s3 sync ./frontend/build s3://$S3_BUCKET_NAME --delete

      - name: Invalidate CloudFront cache
        if: ${{ env.CLOUDFRONT_DIST_ID != '' }}
        run: |
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --paths "/*"

      - name: Install Cypress test dependencies
        working-directory: ./e2e-tests
        run: npm install

      - name: Run Cypress E2E Tests with report
        working-directory: ./e2e-tests
        run: |
          echo "CYPRESS_BASE_URL=$CYPRESS_BASE_URL" >> .env
          echo "CYPRESS_API_URL=$CYPRESS_API_URL" >> .env
          npm run test:report

      - name: Upload Cypress artifacts (screenshots/videos/report)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            e2e-tests/cypress/screenshots/
            e2e-tests/cypress/videos/
            e2e-tests/cypress/reports/
