name: Deploy Frontend and Run E2E Tests

on:
  push:
    branches:
      - team2-geeta

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      CLOUDFRONT_DIST_ID: ${{ secrets.CLOUDFRONT_DIST_ID }}

    steps:
      # Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install frontend dependencies
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      # Build frontend
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      # Deploy to S3
      - name: Deploy frontend to S3
        run: aws s3 sync ./frontend/build s3://$S3_BUCKET_NAME --delete

      # Invalidate CloudFront (optional)
      - name: Invalidate CloudFront cache
        if: ${{ env.CLOUDFRONT_DIST_ID != '' }}
        run: |
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --paths "/*"

      # Install E2E test dependencies
      - name: Install Cypress test dependencies
        working-directory: ./e2e-tests
        run: npm install

      # Run Cypress tests with report
      - name: Run Cypress E2E Tests with report
        working-directory: ./e2e-tests
        run: npm run test:report

      # Upload test artifacts (screenshots/videos/report)
      - name: Upload Cypress artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            e2e-tests/cypress/screenshots/
            e2e-tests/cypress/videos/
            e2e-tests/cypress/reports/
