name: Cypress E2E on Live Site

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      BASE_URL: https://your-live-site.com  # replace with actual live URL

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run Cypress tests on deployed site
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./frontend
          start: ''
          config: baseUrl=${{ env.BASE_URL }}

      - name: Upload Cypress Artifacts on Failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: |
            frontend/cypress/screenshots
            frontend/cypress/videos
