name: Deploy and Run Cypress E2E Tests

on:
  push:
    branches:
      - team6-sujan

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Build Frontend with Environment Variables
        run: |
          cd frontend
          echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" >> .env
          npm run build
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}

      - name: Deploy to S3
        run: |
          aws s3 sync frontend/build/ s3://$S3_BUCKET_NAME --delete
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}

  run-e2e-tests:
    needs: deploy-frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Cypress Dependencies
        run: |
          cd e2e-tests
          npm install

      - name: Set environment variables
        run: |
          echo "CYPRESS_BASE_URL=https://t6.cicdws.bibek-mishra.com.np" > e2e-tests/.env
          echo "CYPRESS_API_URL=${{ secrets.CYPRESS_API_URL }}" >> e2e-tests/.env

      - name: Run Cypress E2E Tests
        run: |
          cd e2e-tests
          npm run cypress:run
