name: Cypress Tests

on:
  workflow_run:
    workflows: 
      - Frontend Deployment
    types:
      - completed

# on:
#   push:
#     branches:
#       - main
#       - 'team6-sufi'  
      
#   pull_request:
#     branches:
#       - main
#       - 'team6-sufi'

jobs:
  test:
    name: Run Cypress E2E Tests
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      CYPRESS_BASE_URL: ${{ vars.CYPRESS_BASE_URL }}
      CYPRESS_API_URL: ${{ vars.CYPRESS_API_URL }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: ⚙️ Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./e2e-tests
        run: npm install

      - name: Install Cypress binary
        working-directory: ./e2e-tests
        run: npx cypress install

      - name: Run Cypress tests
        working-directory: ./e2e-tests
        run: npx cypress run
        continue-on-error: true  # so workflow continues even if tests fail

      - name: Send Slack Notification
        if: always()  # always run, even if previous step fails
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          if [[ "${{ steps.cypress_run.outcome }}" == "success" ]]; then
            STATUS="✅ Cypress tests passed"
          else
            STATUS="🚨 Cypress tests failed"
          fi
          PAYLOAD=$(jq -n --arg text "$STATUS on branch ${{ github.ref_name }}" '{text: $text}')
          curl -sSL -X POST -H 'Content-type: application/json' -d "$PAYLOAD" "$SLACK_WEBHOOK_URL"