name: Cypress Tests

# on:
#   workflow_run:
#     workflows: 
#       - Frontend Deployment
#     types:
#       - completed

on:
  push:
    branches:
      - main
      - 'team6-sufi'  
      
  pull_request:
    branches:
      - main
      - 'team6-sufi'

jobs:
  test:
    name: Run Cypress E2E Tests
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      CYPRESS_BASE_URL: ${{ vars.CYPRESS_BASE_URL }}
      CYPRESS_API_URL: ${{ vars.CYPRESS_API_URL }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: ⚙️ Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./e2e-tests
        run: npm install

      - name: Install Cypress binary
        working-directory: ./e2e-tests
        run: npx cypress install

      - name: Run Cypress tests
        working-directory: ./e2e-tests
        run: npx cypress run

      - name: Notify Slack on Success
        if: success()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "$(jq -n --arg text "✅ Cypress Tests Passed on branch \`${{ github.ref_name }}\`.\nWorkflow: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View logs>" '{text: $text}')" \
          "$SLACK_WEBHOOK_URL"

      - name: Notify Slack on Failure
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "$(jq -n --arg text "🚨 Cypress Tests Failed on branch \`${{ github.ref_name }}\`.\nWorkflow: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View logs>" '{text: $text}')" \
          "$SLACK_WEBHOOK_URL"

  