name: Frontend E2E Tests Post-Deployment

on:
  workflow_run:
    workflows: ["Frontend Deployment"]
    types:
      - completed

jobs:
  e2e-tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'e2e-tests/package-lock.json'

    - name: Install E2E test dependencies
      working-directory: ./e2e-tests
      run: npm ci

    - name: Wait for deployment to be ready
      run: |
        echo "Waiting for frontend to be accessible..."
        timeout 300 bash -c 'until curl -f ${{ secrets.FRONTEND_URL }}; do sleep 10; done'

    - name: Run Cypress E2E tests
      working-directory: ./e2e-tests
      run: npm run cypress:run
      env:
        CYPRESS_BASE_URL: ${{ secrets.FRONTEND_URL }}
        CYPRESS_API_URL: ${{ secrets.BACKEND_API_URL }}

    - name: Upload Cypress artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: cypress-artifacts
        path: |
          e2e-tests/cypress/screenshots
          e2e-tests/cypress/videos
          e2e-tests/cypress/reports

    - name: Send Slack notification
      if: always()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        custom_payload: |
          {
            text: "E2E Tests ${{ job.status == 'success' && 'Passed' || 'Failed' }}!",
            attachments: [{
              color: "${{ job.status == 'success' && 'good' || 'danger' }}",
              fields: [{
                title: "Repository",
                value: "${{ github.repository }}",
                short: true
              }, {
                title: "Branch",
                value: "${{ github.ref_name }}",
                short: true
              }]
            }]
          }
      # env:
      #   SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
